version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./.env_local
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
  database:
    image: "postgres:latest"
    env_file:
      - ./.env_local
