apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${SERVICE}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        autoscaling.knative.dev/minScale: '1'
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/cloudsql-instances: ${SQL_CONNECTION_NAME}
    spec:
      containerConcurrency: 99
      containers:
      - image: ${IMAGE}
        env:
        - name: INSTANCE_UNIX_SOCKET
          valueFrom:
            secretKeyRef:
              key: '3'
              name: cloudsql_socket
        - name: INSTANCE_CONNECTION_NAME
          valueFrom:
            secretKeyRef:
              key: '1'
              name: connection_name
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: '1'
              name: cloudsql_user
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: '1'
              name: cloudsql_db
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: '1'
              name: cloudsql_password
              
  traffic:
  - percent: 100
    latestRevision: true